[package]
name = "rust_module"
version = "0.0.1"
authors = ["Toshiya Nakakura <nakakura@me.com>"]
edition = "2018"

[lib]
name = "rust_module"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.48"
cfg-if = "1.0"
either = {version = "1.6.1", features = ["serde"]}
futures = "0.3"
once_cell = "1.7.2"
serde = { version = "^1.0.101", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
shaku = "0.6.1"
skyway-webrtc-gateway-api = { path = "webrtc_gateway_controller" }
tokio = { version = "1.2.0", features = ["full"] }
tokio-stream = "0.1.5"

[dev-dependencies]
mockall = "0.9.1"
mockall_double = "0.2.0"
mockito = "0.30.0"
reqwest = { version = "0.11.0", features = ["json"] }

[[example]]
name = "data_caller"
path = "examples/data_caller.rs"

[[example]]
name = "data_callee"
path = "examples/data_callee.rs"

[[example]]
name = "media_caller"
path = "examples/media_caller.rs"

[[example]]
name = "media_callee"
path = "examples/meida_callee.rs"

