name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodule Initialize
      run: |
        git submodule init
        git submodule update
    - name: Run tests
      run: |
        git submodule init
        git submodule update
        cargo test --verbose
